### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by Saber-shm** [microsoft/IRNet#56]
i run python3 train.py and it runs for like 10 to 15 min and then gives me this error:

The size of tensor a (300) must match the size of tensor b (100) at non-singleton dimension 2
Traceback (most recent call last):
  File "/mnt/c/Users/Legion/irnet/IRNet/train_test.py", line 56, in train
    loss = utils.epoch_train(model, optimizer, args.batch_size, sql_data, table_data, args,
  File "/mnt/c/Users/Legion/irnet/IRNet/src/utils.py", line 242, in epoch_train
    score = model.forward(examples)
  File "/mnt/c/Users/Legion/irnet/IRNet/src/models/model.py", line 215, in forward
    table_embedding = table_embedding + tab_ctx
RuntimeError: The size of tensor a (300) must match the size of tensor b (100) at non-singleton dimension 2

**Comment by Monte2345** [comment]
the argument “hidden_size” should be set to 300?
